include ~/.cache/wal/colors-kitty.conf

######## Fonts ########

font_size        12.0

font_family             MonoLisa Nerd Font Mono
bold_font               auto
italic_font             auto
bold_italic_font        auto

disable_ligatures       never

modify_font cell_height 25px

######## Cursor ########

cursor_shape underline

######## Tabs ########

tab_bar_style powerline
tab_bar_edge  top
tab_bar_align left
tab_powerline_style slanted

######## Window ########

background_opacity      0.8
background_blur         64

window_padding_width    14
confirm_os_window_close 0

macos_hide_titlebar     yes

######## Keymaps #########

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+f launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id
mouse_map cmd+left click ungrabbed no_op

nnoremap <ScrollWheelRight> <Nop>
nnoremap <ScrollWheelLeft> <Nop>
nnoremap <S-ScrollWheelUp> <ScrollWheelRight>
nnoremap <S-ScrollWheelDown> <ScrollWheelLeft>

######## Shell Integration ########

shell_integration    enabled
shell_integration    no-cursor
allow_remote_control yes
remote_control_password yes
editor               /opt/homebrew/bin/nvim
