# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='#1e1e2e'
foreground='#cdd6f4'
cursor='#cdd6f4'

# Colors
color0='#181825'
color1='#f38ba8'
color2='#89b4fa'
color3='#f9e2af'
color4='#a6e3a1'
color5='#cba6f7'
color6='#fab387'
color7='#cdd6f4'
color8='#313244'
color9='#f38ba8'
color10='#89b4fa'
color11='#f9e2af'
color12='#a6e3a1'
color13='#cba6f7'
color14='#fab387'
color15='#cdd6f4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
