#!/usr/bin/env lua

-- Load the sketchybar-package and prepare the helper binaries
require("/Users/lalit/.config/sketchybar/helpers")
require("/Users/lalit/.config/sketchybar/init")

-- Enable hot reloading
sbar.exec("sketchybar --hotload true")
