--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#1e1e2e"
foreground="#cdd6f4"
cursor="#cdd6f4"

-- Colors
color0="#181825"
color1="#f38ba8"
color2="#89b4fa"
color3="#f9e2af"
color4="#a6e3a1"
color5="#cba6f7"
color6="#fab387"
color7="#cdd6f4"
color8="#313244"
color9="#f38ba8"
color10="#89b4fa"
color11="#f9e2af"
color12="#a6e3a1"
color13="#cba6f7"
color14="#fab387"
color15="#cdd6f4"
