# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='#232136'
foreground='#e0def4'
cursor='#e0def4'

# Colors
color0='#393552'
color1='#eb6f92'
color2='#3e8fb0'
color3='#f6c177'
color4='#9ccfd8'
color5='#c4a7e7'
color6='#ea9a97'
color7='#e0def4'
color8='#6e6a86'
color9='#eb6f92'
color10='#3e8fb0'
color11='#f6c177'
color12='#9ccfd8'
color13='#c4a7e7'
color14='#ea9a97'
color15='#e0def4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
