--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#232136"
foreground="#e0def4"
cursor="#e0def4"

-- Colors
color0="#393552"
color1="#eb6f92"
color2="#3e8fb0"
color3="#f6c177"
color4="#9ccfd8"
color5="#c4a7e7"
color6="#ea9a97"
color7="#e0def4"
color8="#6e6a86"
color9="#eb6f92"
color10="#3e8fb0"
color11="#f6c177"
color12="#9ccfd8"
color13="#c4a7e7"
color14="#ea9a97"
color15="#e0def4"
